apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: huarui_dish
  namespace: local
spec:
  replicas: 1
  template:
    metadata:
     labels:
       app: huarui_dish
    spec:
     containers:
     - name: huarui_dish
       image: c568254965/dish:v1.1
       tty: true
       ports:
       - containerPort: 6822
