server:
    port: 6822



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:6801/eureka/
  instance:  #192.168.1.6
    instance-id: huarui_dishes   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址
spring:

  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: es-from-csrr

      repositories:
        enabled: true

  profiles:
    active: dev
  application:
    name: huaruidishes

  datasource:
    # type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.28.47.9:3306/huarui_res?useSSL=false
    username: root
    password: 123456

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false
mybatis:
  type-aliases-package: com.huarui.model


orderQueue: orderQueue


#mapper:
#  mappers: com.huarui.dao
#  identity: mysql